trigger:
- main

pool:
  name: MD-Surf
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_REPO: 'https://github.com/dfe168/Galawij.com.git'

steps:
- checkout: self

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "dkaban@gmail.com"
      git config --global user.name "Dara Kaban"

      git remote add github $(GITHUB_REPO)
      git push github --mirror
