trigger:
- main

pool:
  name: MD-Surf

variables:
  - group: GithubSecrets
  - name: GITHUB_REPO 
    value: 'https://dfe168:$(github_pat)@github.com/dfe168/Galawij.com.git'

steps:
- checkout: self

- script: |
    git config --global user.email "dkaban@gmail.com"
    git config --global user.name "Dara Kaban"
    git remote add github $(GITHUB_REPO)
    git push github --force
  displayName: 'Push naar GitHub'