name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: dfe168/Galawij.com/.github/workflows/tests.yaml@main

  deploy:
    needs: run-tests
    if: ${{ success() }}
    uses: dfe168/Galawij.com/.github/workflows/deploy.yaml