name: Deploy

on:
  workflow_call:
      
jobs:
  Deploy: 
   runs-on: ubuntu-latest

   steps:
    - name: Checkout Code
      uses: actions/checkout@v4
     
    - name: Run remote shell commands
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            git pull origin main
            php artisan migrate --force
            php artisan optimize



        
