name: Tests

on:
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php_version: 8.3

      - name: Copy .env
        run: |
          cp .env.ci .env

      - name: Run composer
        run: |
          composer Install --no-interaction
          php artisan key:generate
          php artisan migrate --seed

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build
        
      - name: Clear Laravel caches
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      - name: Reun tests 
        run: |
          php artisan test
        continue-on-error: true


      
